//
// Comments.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** list of comments */
public struct Comments: Codable { 


    public var data: [Comment]?

    public init(data: [Comment]?) {
        self.data = data
    }

}
