//
// Posts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** list of posts */
public struct Posts: Codable { 


    public var data: [Post]?

    public init(data: [Post]?) {
        self.data = data
    }

}
