//
// Users.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** list of all users */
public struct Users: Codable { 


    public var data: [User]?

    public init(data: [User]?) {
        self.data = data
    }

}
