//
// Post.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Post: Codable { 


    public var text: String?
    /** image url */
    public var image: String?
    /** amount of likes, initial value 0 */
    public var likes: Double?
    /** url to the post */
    public var link: String?
    /** list of tags */
    public var tags: [Tag]?
    public var publishDate: String?
    public var owner: User?

    public init(text: String?, image: String?, likes: Double?, link: String?, tags: [Tag]?, publishDate: String?, owner: User?) {
        self.text = text
        self.image = image
        self.likes = likes
        self.link = link
        self.tags = tags
        self.publishDate = publishDate
        self.owner = owner
    }

}
