//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Tag: Codable { 
    public var title: String?

    public init(title: String?) {
        self.title = title
    }

}
