//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct User: Codable { 


    public enum Title: String, Codable, CaseIterable {
        case mr = "mr"
        case ms = "ms"
        case mrs = "mrs"
        case miss = "miss"
        case dr = "dr"
    }
    public enum Gender: String, Codable, CaseIterable {
        case male = "male"
        case female = "female"
        case other = "other"
    }
    public var id: String?
    public var title: Title?
    public var firstName: String?
    public var lastName: String?
    public var gender: Gender?
    public var email: String?
    public var location: Location?
    public var dateOfBirth: String?
    public var registerDate: String?
    /** phone number in any format */
    public var phone: String?
    /** image url */
    public var picture: String?

    public init(id: String?, title: Title?, firstName: String?, lastName: String?, gender: Gender?, email: String?, location: Location?, dateOfBirth: String?, registerDate: String?, phone: String?, picture: String?) {
        self.id = id
        self.title = title
        self.firstName = firstName
        self.lastName = lastName
        self.gender = gender
        self.email = email
        self.location = location
        self.dateOfBirth = dateOfBirth
        self.registerDate = registerDate
        self.phone = phone
        self.picture = picture
    }

}
